/**
 * The collection. Loaded into the database on first run (see server/db.ts). Images live in public/art.
 *
 * Titles and descriptions are written from what each painting shows.
 * Year, canvas size, price and status are PLACEHOLDERS (sizes are estimated
 * from each photo's proportions); replace them with the real details.
 */
const art = (file) => `/art/${file}.jpg`;
export const seedArtworks = [
    {
        id: 'peaches-and-cherries',
        title: 'Peaches and Cherries',
        year: 2024,
        medium: 'Oil on canvas',
        dimensions: '28 x 36 cm',
        price: 1450,
        status: 'available',
        image: art('peaches-and-cherries'),
        story: 'A brass bowl heaped with ripe peaches, two more resting on the ledge beside a sprig of cherries. Warm light falls from the left, picking out the gold rim of the bowl and the soft blush of each fruit against a deep, dark ground.',
    },
    {
        id: 'the-falls',
        title: 'The Falls',
        year: 2024,
        medium: 'Oil on canvas',
        dimensions: '30 x 60 cm',
        price: 1600,
        status: 'reserved',
        image: art('the-falls'),
        story: 'A wide panorama of white water pouring over rust-colored rocks. The spray is built up in thick, broken strokes of white and turquoise, so the surface of the paint itself seems to move.',
    },
    {
        id: 'still-life-with-grapes-and-plate',
        title: 'Still Life with Grapes and Plate',
        year: 2024,
        medium: 'Oil on canvas',
        dimensions: '30 x 40 cm',
        price: 1200,
        status: 'sold',
        image: art('still-life-with-grapes-and-plate'),
        story: 'Black and green grapes spill across a white cloth between a pomegranate, a plum, two peaches and an apple, with a green glass bottle and an upturned plate standing behind. A signed, classical table arrangement in warm, even light.',
    },
    {
        id: 'breaking-wave',
        title: 'Breaking Wave',
        year: 2024,
        medium: 'Oil on canvas',
        dimensions: '30 x 40 cm',
        price: 1350,
        status: 'available',
        image: art('breaking-wave'),
        story: 'A green wave rises between orange rocks as two sailboats hold their course out at sea. The light passes through the curl of the water, and the foam is laid on thickly with the brush.',
    },
    {
        id: 'red-roses-in-a-white-pot',
        title: 'Red Roses in a White Pot',
        year: 2024,
        medium: 'Oil on canvas',
        dimensions: '23 x 30 cm',
        price: 780,
        status: 'available',
        image: art('red-roses-in-a-white-pot'),
        story: 'Red roses crowd a blue-striped stoneware pot, with a loose spray of yellow roses and small wildflowers laid on the shelf beside it and a cluster of green grapes at the left.',
    },
    {
        id: 'pink-roses',
        title: 'Pink Roses',
        year: 2024,
        medium: 'Oil on canvas, framed',
        dimensions: '25 x 20 cm',
        price: 850,
        status: 'sold',
        image: art('pink-roses-framed'),
        story: 'Full pink roses in a tall white vase banded with blue, a few fallen petals on the table below. Signed at lower left. Sold in a carved dark wood frame.',
    },
    {
        id: 'green-bottle-and-grapes',
        title: 'Green Bottle and Grapes',
        year: 2024,
        medium: 'Oil on canvas',
        dimensions: '23 x 30 cm',
        price: 820,
        status: 'available',
        image: art('green-bottle-and-grapes'),
        story: 'A red apple, two bunches of grapes and a peach gathered in front of a green bottle and a tilted white dish, with a drape of white cloth falling at the right. Painted loosely, with bright highlights on every grape.',
    },
    {
        id: 'boats-at-sunset',
        title: 'Boats at Sunset',
        year: 2024,
        medium: 'Oil on canvas',
        dimensions: '25 x 20 cm',
        price: 690,
        status: 'available',
        image: art('boats-at-sunset'),
        story: 'Three rowing boats pulled up on the sand while an orange sky turns the whole bay gold. Gulls cross overhead and the surf breaks against a dark headland of rock.',
    },
    {
        id: 'sunflower',
        title: 'Sunflower',
        year: 2024,
        medium: 'Oil on canvas',
        dimensions: '25 x 20 cm',
        price: 620,
        status: 'available',
        image: art('sunflower'),
        story: 'A single sunflower fills the canvas against a soft lilac and blue sky. The seed head is worked in heavy, textured paint and the petals in quick, confident strokes.',
    },
    {
        id: 'cottage-by-the-stream',
        title: 'Cottage by the Stream',
        year: 2024,
        medium: 'Oil on canvas',
        dimensions: '23 x 30 cm',
        price: 890,
        status: 'available',
        image: art('cottage-by-the-stream'),
        story: 'A whitewashed cottage with a thatched roof sits in a meadow of wildflowers. Smoke rises from the chimney, a ladder leans on the wall, and a figure kneels to wash clothes at the edge of the stream.',
    },
    {
        id: 'houses-by-the-river',
        title: 'Houses by the River',
        year: 2024,
        medium: 'Oil on canvas',
        dimensions: '20 x 25 cm',
        price: 760,
        status: 'available',
        image: art('houses-by-the-river'),
        story: 'Two farmhouses stand at the edge of a pine forest, washing drying on the line and more laid out on the riverbank rocks. The river runs fast and pale across the foreground. Initialled at lower right.',
    },
    {
        id: 'two-pears-and-cherries',
        title: 'Two Pears and Cherries',
        year: 2024,
        medium: 'Oil on canvas',
        dimensions: '30 x 23 cm',
        price: 720,
        status: 'available',
        image: art('two-pears-and-cherries'),
        story: 'Two ripe pears lean together on a wooden board with three red cherries at their feet, set against a near-black background that makes the yellows glow.',
    },
    {
        id: 'yellow-roses-in-a-blue-vase',
        title: 'Yellow Roses in a Blue Vase',
        year: 2024,
        medium: 'Oil on canvas',
        dimensions: '25 x 20 cm',
        price: 680,
        status: 'available',
        image: art('yellow-roses-in-a-blue-vase'),
        story: 'A generous bunch of yellow roses in a turquoise vase, set on a white and lilac cloth against a black ground. The petals are thick with paint, and a few have dropped onto the table.',
    },
    {
        id: 'jar-apple-and-lemon',
        title: 'Jar, Apple and Lemon',
        year: 2024,
        medium: 'Oil on canvas',
        dimensions: '20 x 25 cm',
        price: 640,
        status: 'available',
        image: art('jar-apple-and-lemon'),
        story: 'A glass jar of sweets with a wooden lid, a red apple, a small lemon and a lidded white bowl, with folded papers behind. A careful study of glass, porcelain and fruit in side light.',
    },
    {
        id: 'swans-in-the-shade',
        title: 'Swans in the Shade',
        year: 2024,
        medium: 'Oil on canvas',
        dimensions: '20 x 20 cm',
        price: 560,
        status: 'available',
        image: art('swans-in-the-shade'),
        story: 'Three white swans glide across a green pond beneath hanging willow branches, the far bank lined with pale, lichen-covered stones.',
    },
    {
        id: 'red-and-yellow-roses',
        title: 'Red and Yellow Roses',
        year: 2024,
        medium: 'Oil on canvas',
        dimensions: '25 x 20 cm',
        price: 650,
        status: 'available',
        image: art('red-and-yellow-roses'),
        story: 'Three red and three yellow roses gathered in a clear glass vase, their stems visible through the water, floating on a soft grey-blue ground.',
    },
    {
        id: 'flowers-on-the-table',
        title: 'Flowers on the Table',
        year: 2024,
        medium: 'Oil on canvas',
        dimensions: '20 x 25 cm',
        price: 700,
        status: 'available',
        image: art('flowers-on-the-table'),
        story: 'Cut flowers in red, yellow, white and violet laid across the edge of a table, painted with rich, loaded strokes against a pale, cloudy background.',
    },
    {
        id: 'the-yellow-bird',
        title: 'The Yellow Bird',
        year: 2024,
        medium: 'Oil on canvas',
        dimensions: '25 x 20 cm',
        price: 740,
        status: 'available',
        image: art('the-yellow-bird'),
        story: 'A bright yellow songbird with a red face and blue wings perches on a tree stump beside pink blossoms, with blue-grey mountains and clouds behind.',
    },
    {
        id: 'bouquet-in-a-blue-jar',
        title: 'Bouquet in a Blue Jar',
        year: 2024,
        medium: 'Oil on canvas',
        dimensions: '30 x 23 cm',
        price: 780,
        status: 'available',
        image: art('bouquet-in-a-blue-jar'),
        story: 'A mixed bouquet of red, yellow, violet and white blooms in a deep blue glazed jar, petals scattered on a white cloth against a warm ochre wall.',
    },
    {
        id: 'sunset-over-the-river',
        title: 'Sunset over the River',
        year: 2024,
        medium: 'Oil on canvas',
        dimensions: '30 x 25 cm',
        price: 720,
        status: 'available',
        image: art('sunset-over-the-river'),
        story: 'An orange sun sets between dense green trees, and its light runs down the still river below. Birds cross the glowing sky at the top of the canvas.',
    },
];
